# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "531a3e4261ba3a9310ec65c7a8fe688e"
application_url = "https://example.com"
embedded = true
name = "refund-webhook-app"

[webhooks]
api_version = "2026-07"



[access_scopes]
scopes = "read_orders,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true